MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  BODY_UV_ON: True
  MASK_ON: False
  PARSING_ON: True
VIS: False
VIS_TH: 0.7
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  GAMMA: 0.1
  WARM_UP_ITERS: 1000
  WARM_UP_FACTOR: 0.1
  # Linear scaling rule:
  # 1 GPU:
  #BASE_LR: 0.00025
  #MAX_ITER: 720000
  #STEPS: [0, 480000, 640000]
  # 2 GPUs:
  #BASE_LR: 0.001 #0.0005
  #MAX_ITER: 520000 #360000
  #STEPS: [0, 400000, 480000]  #[0, 240000, 320000]
  # 4 GPUs:
  BASE_LR: 0.002
  MAX_ITER: 260000
  STEPS: [0, 200000, 240000]
  #8 GPUs:
  # BASE_LR: 0.002
  # MAX_ITER: 130000
  # STEPS: [0, 100000, 120000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs  # Note: this is a GN mask head
  RESOLUTION: 28  # (output mask resolution) default 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14  # default 7
  ROI_XFORM_SAMPLING_RATIO: 2  # default 0
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default GaussianFill
  DP_CASCADE_MASK_ON: False
BODY_UV_RCNN:
  ROI_HEAD: body_uv_rcnn_heads.add_roi_body_uv_head_v1convX_parallroires
  NUM_STACKED_CONVS: 8
  NUM_PATCHES: 19 # 19 CIHP #58 for mhp #24 for coco
  USE_DECONV_OUTPUT: True
  CONV_INIT: GaussianFill
  CONV_HEAD_DIM: 256
  UP_SCALE: 2
  HEATMAP_SIZE: 56
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2

  ##
  # Loss weights for annotation masks.(14 Parts)
  INDEX_WEIGHTS : 2.0
  # Loss weights for surface parts. (24 Parts)  
  PART_WEIGHTS : 0.3
  # Loss weights for UV regression.
  POINT_REGRESSION_WEIGHTS : 0.1
  ##
  BODY_UV_IMS: True 
  SOFT_MASK_THRESH: 0.3
  MULTI_ROI: True
  MULTI_LEVEL_RES: [7,14,14,28]
  INTERMEDIA_SUPER: True
  ONLY_PARTSEG: True
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  #DATASETS: ('dense_coco_2014_train', 'dense_coco_2014_valminusminival')
  DATASETS: ('CIHP_seg_train',) # CIHP_seg_train #MHP_seg_train
  SCALES: (640, 672, 704, 736, 768,800)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 2
  BATCH_SIZE_PER_IM: 128 #128
  USE_FLIPPED: True
  RPN_PRE_NMS_TOP_N: 1000 #1000  # Per FPN level
TEST:
  DATASETS: ('CIHP_seg_val',) #('dense_coco_2014_minival',) #CIHP_seg_val #MHP_seg_val
  PROPOSAL_LIMIT: 1000
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  FORCE_JSON_DATASET_EVAL: True
  DETECTIONS_PER_IM: 20
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level 
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: ''
